<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <IsPackable>true</IsPackable>

        <AssemblyName>PANiXiDA.Core.SpecificationPattern</AssemblyName>

        <PackageId>PANiXiDA.Core.SpecificationPattern</PackageId>
        <Description>A library for implementing the Specification pattern in .NET applications with reusable business rules, composable filtering logic, and support for clean domain-driven design.</Description>
        <PackageTags>Specification;SpecificationPattern;DDD;DomainDrivenDesign;BusinessRules;Filtering;Querying;DotNet</PackageTags>

        <RepositoryUrl>https://github.com/panixida-dotnet-core/specification-pattern</RepositoryUrl>
        <PackageProjectUrl>https://github.com/panixida-dotnet-core/specification-pattern</PackageProjectUrl>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Nerdbank.GitVersioning">
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
    </ItemGroup>
</Project>
